### ISSUE TITLE
lib/write/append fails to find argument

### ISSUE THREAD

**Issue by gchiu** [metaeducation/rebol-httpd#10]
I was seeing this error

```
6-Feb-2020/21:24:29.807337+0:00 make error! [
    type: 'Script
    id: 'no-catch
    message: ["No CATCH for THROW of" :arg1 "with /NAME:" :arg2]
    near: [
        wait [srv] ~~]
    where: [wait trap do catch either else _ do console]
    file: 'server.reb
    line: 104
    arg1: '
    arg2: 'make action! [[] [...]]
]
```
which was solved using

```
w*: :lib/write
... and then in server event code
w*/append %logs/log.txt spaced [now/precise mold err newline]
; instead of using
lib/write/append %logs/log.txt spaced [...]
```

I will attempt to write a minimal case later on.

**Comment by gchiu** [comment]
Here's minimal server code to repro this bug.  See https://gitlab.com/Zhaoshirong/rebol-chat/-/blob/master/src/s.reb#L28 which fixes it, and uncommenting https://gitlab.com/Zhaoshirong/rebol-chat/-/blob/master/src/s.reb#L27 causes it.  See commit a42eebfbc4e5da08e791a014270acfc62ff055d4

**Comment by hostilefork** [comment]
I get different behavior here depending on whether I run `do` on the script from the console vs. if I run the script on the command-line.

Is that the case for you as well?  e.g. does the "broken" version work as expected when you get a console prompt and then run DO?

**Comment by gchiu** [comment]
I've only ever used it as a command line script

```
sudo /sbin/r3 s.reb
```

**Comment by hostilefork** [comment]
Problem came down to an issue with newlines not being preserved by LOAD on paths of length > 2:

    >> load "--^/a/b"
    == [--
        a/b]

     >> load "--^/a/b/c"
     == [-- a/b/c]

So what was happening is your `--` dumper was picking up the `lib/write/append` and evaluating it in isolation with no arguments.

Fixed here:

https://github.com/metaeducation/ren-c/commit/c06e41534f4fc92419b719a00ae6b718d1c460dd
