### ISSUE TITLE
httpd crash using chrome client

### ISSUE THREAD

**Issue by gchiu** [metaeducation/rebol-httpd#7]
Problem seems to be in the networking stack with extraneous read event and no data received.

Posted from https://github.com/metaeducation/ren-c/issues/1045

```
>> do https://raw.githubusercontent.com/metaeducation/rebol-httpd/master/httpd.reb
Module: Web Server Scheme for Ren-C Version: 0.3.5 Date: 13-Sep-2019

>> srv: open [scheme: 'httpd 8888 [probe request/action]] wait [srv]
"GET /index.html"
(i) Info: use WHY for error information
** Access Error: port is not open: [scheme: 'tcp]
** Where: read default case switch _ wake-up if while _ wait console
** Near: [read client ~~]
** File: https://raw.githubusercontent.com/metaeducation/rebol-httpd/master/httpd.reb
** Line: 58
```

And from http://hostilefork.com/media/shared/replpad-js/

```
>> 	to text! read http://localhost:8888/index.html
** Error: TypeError: Failed to fetch
‌** Where: read-url-helper if read main
‌** Near: [... text! CORSify-if-gitlab-url source ~~]
‌** Line: 329
```

**Comment by hostilefork** [comment]
Attempt to address this is in:

https://github.com/metaeducation/rebol-httpd/pull/8

However I think there is likely a better solution.

**Comment by gchiu** [comment]
Here's how to reproduce this error:
On R3
```
>> import <httpd> ()
== make module! [
    net-utils: [
        net-log _
    ]
    as-text: 'make action! [[binary] [...]]
]

>> srv: open [scheme: 'httpd 8081 [render "ehlo"]] wait [srv]
```

and then on R2
```
>> p: open tcp://localhost:8081
>> insert p "GET /"
>> close p
```

and the error in R3 is

```
(i) Info: use WHY for error information
** Access Error: port is not open: [scheme: 'tcp]
** Where: read if default case switch _ wake-up if while _ wait console
** Near: [read client ~~]
** Line: 29
```

**Comment by hostilefork** [comment]
I can reproduce this on Windows, but not on Linux.

If you take out your patch, did you ever see this on Linux?

**Comment by hostilefork** [comment]
Here's an attempt at fixing the specific problem of READ events being sent on 0 byte "reads" (that are actually clean socket closes hung up by the client):

https://github.com/metaeducation/ren-c/commit/e9d55b923bde4e8bb4a0e27cf9ec0812d03bb424

Hopefully this will resolve the issue.  If not, reopen and let me know.
